import { supabase } from './supabase.js';
const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3000)};
async function isAdmin(){const {data:user}=await supabase.auth.getUser();if(!user?.user)return false;const {data}=await supabase.from('admins').select('user_id').eq('user_id',user.user.id).maybeSingle();return !!data}
async function boot(){if(!(await isAdmin())){ $('#login').hidden=false;$('#panel').hidden=true;return } $('#login').hidden=true;$('#panel').hidden=false;await load();}
async function load(){const [r,d,a]=await Promise.all([supabase.from('driver_requests').select('id,name,phone,whatsapp,car_model,plate_number,out_trips,notes,status,created_at,areas(name),car_types(name)').order('created_at',{ascending:false}),supabase.from('drivers').select('id'),supabase.from('areas').select('id')]);if(r.error||d.error||a.error){toast('تعذر تحميل لوحة الإدارة');return}const pending=(r.data||[]).filter(x=>x.status==='pending');$('#pendingCount').textContent=pending.length;$('#adminDrivers').textContent=(d.data||[]).length;$('#adminAreas').textContent=(a.data||[]).length;$('#requests').innerHTML=pending.length?pending.map(requestCard).join(''):'<div class="empty">لا توجد طلبات معلقة.</div>';document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>review(b.dataset.approve,'approved'));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>review(b.dataset.reject,'rejected'));}
function requestCard(r){return `<article class="driver" style="margin-bottom:12px"><div class="driver-head"><h3>${esc(r.name)}</h3><span class="badge">معلق</span></div><div class="meta"><span>📞 ${esc(r.phone)}</span><span>📍 ${esc(r.areas?.name||'غير محدد')}</span><span>🚗 ${esc(r.car_types?.name||'غير محدد')} ${esc(r.car_model||'')}</span><span>🪪 ${esc(r.plate_number||'غير مذكور')}</span>${r.out_trips?'<span>🛣️ سفر خارج الشرقاط</span>':''}${r.notes?`<span>📝 ${esc(r.notes)}</span>`:''}</div><div class="actions"><button class="call" data-approve="${r.id}">اعتماد</button><button class="rate" data-reject="${r.id}">رفض</button></div></article>`}
async function review(id,status){let reason=null;if(status==='rejected'){reason=prompt('سبب الرفض (اختياري)')||null}const {data:req,error}=await supabase.from('driver_requests').select('*').eq('id',id).single();if(error)return toast('تعذر قراءة الطلب');const {data:user}=await supabase.auth.getUser();if(status==='approved'){const {error:e}=await supabase.from('drivers').insert({name:req.name,phone:req.phone,whatsapp:req.whatsapp,area_id:req.area_id,car_type_id:req.car_type_id,car_model:req.car_model,plate_number:req.plate_number,out_trips:req.out_trips,notes:req.notes,status:'active',verified:false});if(e)return toast('تعذر اعتماد السائق');}const {error:u}=await supabase.from('driver_requests').update({status,rejection_reason:reason,reviewed_at:new Date().toISOString(),reviewed_by:user.user.id}).eq('id',id);if(u)return toast('تم إنشاء السائق لكن تعذر تحديث الطلب');await supabase.from('activity_logs').insert({admin_user_id:user.user.id,action:status==='approved'?'approve_driver':'reject_driver',entity_type:'driver_request',entity_id:id,details:{reason}});toast(status==='approved'?'تم اعتماد السائق':'تم رفض الطلب');await load();}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.auth.signInWithPassword({email:f.get('email'),password:f.get('passcode')});if(error){$('#loginMsg').textContent='بيانات الدخول غير صحيحة أو الحساب غير مصرح له.';return}$('#loginMsg').textContent='';await boot()};
$('#logout').onclick=async()=>{await supabase.auth.signOut();await boot()};$('#refresh').onclick=load;supabase.auth.onAuthStateChange(()=>boot());boot();
