import { supabase } from './supabase.js';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3000)};
const activeStatuses=['assigned','accepted','arriving','arrived','in_progress'];
const statusText={pending:'جديد',searching:'جاري البحث',assigned:'تم التعيين',accepted:'مقبولة',arriving:'بالطريق',arrived:'وصلت',in_progress:'قيد الرحلة',completed:'مكتملة',cancelled:'ملغاة'};
let driver=null;
async function getDriver(){const {data:{user}}=await supabase.auth.getUser();if(!user)return null;const {data,error}=await supabase.from('drivers').select('id,name,phone,status,auth_user_id').eq('auth_user_id',user.id).maybeSingle();if(error)console.error(error);return data||null}
async function boot(){driver=await getDriver();if(!driver){$('#login').hidden=false;$('#panel').hidden=true;$('#loginMsg').textContent='هذا الحساب غير مرتبط بسائق. اطلب من الإدارة ربط حسابك.';return}$('#login').hidden=true;$('#panel').hidden=false;$('#driverName').textContent=`أهلاً ${driver.name}`;renderDriverStatus();await loadTrips()}
function renderDriverStatus(){const online=driver.status==='active';$('#statusBadge').textContent=online?'🟢 متاح':'⚫ غير متاح';$('#statusBadge').className=`badge ${online?'':'busy'}`;$('#toggleOnline').textContent=online?'إيقاف استقبال الطلبات':'متاح لاستقبال الطلبات'}
async function toggleOnline(){const next=driver.status==='active'?'inactive':'active';const {error}=await supabase.from('drivers').update({status:next}).eq('id',driver.id);if(error)return toast('تعذر تغيير الحالة.');driver.status=next;renderDriverStatus();await loadTrips();toast(next==='active'?'أصبحت متاحاً للطلبات.':'تم إيقاف استقبال الطلبات.')}
async function loadTrips(){
 const {data,error}=await supabase.from('trip_requests').select('id,public_code,customer_name,customer_phone,pickup_text,destination_text,scheduled_at,estimated_price,status,notes,created_at,services(name,icon)').or(`status.in.(pending,searching),driver_id.eq.${driver.id}`).order('created_at',{ascending:false}).limit(50);
 if(error){console.error(error);toast('تعذر تحميل الرحلات.');return}
 const rows=data||[], current=rows.filter(x=>x.driver_id===driver.id&&activeStatuses.includes(x.status))[0], available=driver.status==='active'?rows.filter(x=>!x.driver_id&&['pending','searching'].includes(x.status)):[], history=rows.filter(x=>x.driver_id===driver.id&&['completed','cancelled'].includes(x.status));
 $('#availableTrips').innerHTML=available.length?available.map(availableCard).join(''):(driver.status==='active'?'<div class="empty">لا توجد طلبات جديدة حالياً.</div>':'<div class="empty">فعّل حالتك لاستقبال الطلبات.</div>');
 $('#currentTrip').innerHTML=current?tripCard(current,true):'<div class="empty">لا توجد رحلة حالية.</div>';
 $('#history').innerHTML=history.length?history.map(x=>tripCard(x,false)).join(''):'<div class="empty">لا توجد رحلات مكتملة بعد.</div>';
 document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>acceptTrip(b.dataset.accept));document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>advanceTrip(b.dataset.next,b.dataset.status));
}
function availableCard(t){const s=t.services?.name||'رحلة';return `<article class="driver" style="margin-bottom:12px"><div class="driver-head"><h3>${esc(t.services?.icon||'🚕')} ${esc(t.public_code)}</h3><span class="badge">طلب جديد</span></div><div class="meta"><span>👤 ${esc(t.customer_name)}</span><span>📞 ${esc(t.customer_phone)}</span><span>🚕 ${esc(s)}</span><span>📍 ${esc(t.pickup_text)}</span>${t.destination_text?`<span>🏁 ${esc(t.destination_text)}</span>`:''}${t.scheduled_at?`<span>🕒 ${new Date(t.scheduled_at).toLocaleString('ar-IQ')}</span>`:''}${t.notes?`<span>📝 ${esc(t.notes)}</span>`:''}</div><div class="actions"><button class="primary" data-accept="${t.id}">قبول الطلب</button></div></article>`}
function tripCard(t,current){let next=null;if(current){if(t.status==='assigned')next=['accepted','قبول الرحلة'];else if(t.status==='accepted')next=['arriving','أنا بالطريق'];else if(t.status==='arriving')next=['arrived','وصلت للزبون'];else if(t.status==='arrived')next=['in_progress','بدء الرحلة'];else if(t.status==='in_progress')next=['completed','إنهاء الرحلة'];}return `<article class="driver" style="margin-bottom:12px"><div class="driver-head"><h3>${esc(t.services?.icon||'🚕')} ${esc(t.public_code)}</h3><span class="badge">${esc(statusText[t.status]||t.status)}</span></div><div class="meta"><span>👤 ${esc(t.customer_name)} · ${esc(t.customer_phone)}</span><span>📍 ${esc(t.pickup_text)}</span>${t.destination_text?`<span>🏁 ${esc(t.destination_text)}</span>`:''}${t.estimated_price!=null?`<span>💰 ${esc(t.estimated_price)} ${esc(t.currency||'د.ع')}</span>`:''}</div><div class="actions"><a class="call" href="tel:${encodeURIComponent(t.customer_phone||'')}">اتصال بالزبون</a>${next?`<button class="primary" data-next="${t.id}" data-status="${next[0]}">${next[1]}</button>`:''}</div></article>`}
async function acceptTrip(id){const {data,error}=await supabase.from('trip_requests').update({driver_id:driver.id,status:'accepted',accepted_at:new Date().toISOString()}).eq('id',id).in('status',['pending','searching']).is('driver_id',null).select('id').maybeSingle();if(error||!data)return toast('الطلب أُخذ من سائق آخر أو تعذر قبوله.');await loadTrips();toast('تم قبول الرحلة بنجاح.')}
async function advanceTrip(id,status){const patch={status};if(status==='completed')patch.completed_at=new Date().toISOString();const {error}=await supabase.from('trip_requests').update(patch).eq('id',id).eq('driver_id',driver.id);if(error)return toast('تعذر تحديث الرحلة.');await loadTrips();toast('تم تحديث حالة الرحلة.')}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error){$('#loginMsg').textContent='بيانات الدخول غير صحيحة.';return}await boot()};
$('#toggleOnline').onclick=toggleOnline;$('#refresh').onclick=loadTrips;$('#logout').onclick=async()=>{await supabase.auth.signOut();driver=null;await boot()};supabase.auth.onAuthStateChange(()=>boot());boot();